//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.29 at 06:51:07 PM WEST 
//

package pt.jma.orchestration.context.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;

@XmlAccessorType(XmlAccessType.FIELD)
public class ConverterType {

	@XmlAttribute
	protected String name;
	@XmlAttribute(name = "class")
	protected String clazz;

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

	public String getClazz() {
		return clazz;
	}

	public void setClazz(String value) {
		this.clazz = value;
	}

}
