//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.29 at 07:01:16 PM WEST 
//

package pt.jma.orchestration.activity.config;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = { "inputBind", "outputBind" })
public class BindsType {

	@XmlElementWrapper(name = "input", namespace = "urn:pt.jma.orchestration.activity")
	@XmlElement(name = "bind", type = BindType.class, required = true, namespace = "urn:pt.jma.orchestration.activity")
	protected List<BindType> inputBind;

	public List<BindType> getInputBind() {
		if (inputBind == null) {
			inputBind = new ArrayList<BindType>();
		}
		return this.inputBind;
	}

	@XmlElementWrapper(name = "output", namespace = "urn:pt.jma.orchestration.activity")
	@XmlElement(name = "bind", type = BindType.class, required = true, namespace = "urn:pt.jma.orchestration.activity")
	protected List<BindType> outputBind;

	public List<BindType> getOutputBind() {
		if (outputBind == null) {
			outputBind = new ArrayList<BindType>();
		}
		return this.outputBind;
	}

}
